const PANELI = {
  inox: [
    require("./Img/Paneli/InoxPaneli/1.jpg").default,
    require("./Img/Paneli/InoxPaneli/2.png").default,
    require("./Img/Paneli/InoxPaneli/3.png").default,
    require("./Img/Paneli/InoxPaneli/4.jpg").default,
    require("./Img/Paneli/InoxPaneli/6.jpg").default,
    require("./Img/Paneli/InoxPaneli/7.jpg").default,
    require("./Img/Paneli/InoxPaneli/9.jpg").default,
    require("./Img/Paneli/InoxPaneli/11.jpg").default,
    require("./Img/Paneli/InoxPaneli/12.jpg").default,
    require("./Img/Paneli/InoxPaneli/13.jpg").default,
    require("./Img/Paneli/InoxPaneli/14.jpg").default,
    require("./Img/Paneli/InoxPaneli/15.jpg").default,
    require("./Img/Paneli/InoxPaneli/16.jpg").default,
    require("./Img/Paneli/InoxPaneli/17.jpg").default,
    require("./Img/Paneli/InoxPaneli/18.jpg").default,
    require("./Img/Paneli/InoxPaneli/19.jpg").default,
    require("./Img/Paneli/InoxPaneli/20.jpg").default,
    require("./Img/Paneli/InoxPaneli/5.jpg").default,
    require("./Img/Paneli/InoxPaneli/8.jpg").default,
    require("./Img/Paneli/InoxPaneli/10.jpg").default,
  ],
  premium: [
    require("./Img/Paneli/PremiumPaneli/1.jpg").default,
    require("./Img/Paneli/PremiumPaneli/2.jpg").default,
    require("./Img/Paneli/PremiumPaneli/3.jpg").default,

    require("./Img/Paneli/PremiumPaneli/5.jpg").default,

    require("./Img/Paneli/PremiumPaneli/7.jpg").default,

    require("./Img/Paneli/PremiumPaneli/9.jpg").default,
    require("./Img/Paneli/PremiumPaneli/10.jpg").default,

    require("./Img/Paneli/PremiumPaneli/12.jpg").default,
    require("./Img/Paneli/PremiumPaneli/13.jpg").default,
    require("./Img/Paneli/PremiumPaneli/14.jpg").default,

    require("./Img/Paneli/PremiumPaneli/16.jpg").default,
    require("./Img/Paneli/PremiumPaneli/17.jpg").default,
    require("./Img/Paneli/PremiumPaneli/18.png").default,
    require("./Img/Paneli/PremiumPaneli/19.png").default,
    require("./Img/Paneli/PremiumPaneli/20.png").default,
    require("./Img/Paneli/PremiumPaneli/21.jpg").default,
    require("./Img/Paneli/PremiumPaneli/22.jpg").default,
    require("./Img/Paneli/PremiumPaneli/23.jpg").default,
    require("./Img/Paneli/PremiumPaneli/24.jpg").default,
    require("./Img/Paneli/PremiumPaneli/25.jpg").default,
    require("./Img/Paneli/PremiumPaneli/26.jpg").default,
    require("./Img/Paneli/PremiumPaneli/27.jpg").default,
    require("./Img/Paneli/PremiumPaneli/4.jpg").default,
    require("./Img/Paneli/PremiumPaneli/6.jpg").default,
    require("./Img/Paneli/PremiumPaneli/8.jpg").default,
    require("./Img/Paneli/PremiumPaneli/11.jpg").default,
    require("./Img/Paneli/PremiumPaneli/15.jpg").default,
  ],
  aluminium: [
    require("./Img/Paneli/AluminiumPaneli/1.jpg").default,
    require("./Img/Paneli/AluminiumPaneli/2.jpg").default,
    require("./Img/Paneli/AluminiumPaneli/3.jpg").default,
    require("./Img/Paneli/AluminiumPaneli/4.jpg").default,
    require("./Img/Paneli/AluminiumPaneli/5.jpg").default,
    require("./Img/Paneli/AluminiumPaneli/6.jpg").default,
    require("./Img/Paneli/AluminiumPaneli/7.jpg").default,
    require("./Img/Paneli/AluminiumPaneli/8.jpg").default,
    require("./Img/Paneli/AluminiumPaneli/9.jpg").default,
    require("./Img/Paneli/AluminiumPaneli/10.jpg").default,
    require("./Img/Paneli/AluminiumPaneli/11.jpg").default,
    require("./Img/Paneli/AluminiumPaneli/13.jpg").default,
    require("./Img/Paneli/AluminiumPaneli/14.jpg").default,
    require("./Img/Paneli/AluminiumPaneli/16.jpg").default,
    require("./Img/Paneli/AluminiumPaneli/17.jpg").default,
    require("./Img/Paneli/AluminiumPaneli/12.jpg").default,
    require("./Img/Paneli/AluminiumPaneli/15.jpg").default,
  ],
  elegant: [
    require("./Img/Paneli/ElegantPaneli/1.jpg").default,
    require("./Img/Paneli/ElegantPaneli/2.png").default,
    require("./Img/Paneli/ElegantPaneli/3.png").default,
    require("./Img/Paneli/ElegantPaneli/5.png").default,
    require("./Img/Paneli/ElegantPaneli/7.jpg").default,
    require("./Img/Paneli/ElegantPaneli/8.png").default,
    require("./Img/Paneli/ElegantPaneli/9.png").default,
    require("./Img/Paneli/ElegantPaneli/10.png").default,
    require("./Img/Paneli/ElegantPaneli/11.png").default,
    require("./Img/Paneli/ElegantPaneli/12.png").default,
    require("./Img/Paneli/ElegantPaneli/13.png").default,
    require("./Img/Paneli/ElegantPaneli/14.png").default,
    require("./Img/Paneli/ElegantPaneli/15.png").default,
    require("./Img/Paneli/ElegantPaneli/16.png").default,
    require("./Img/Paneli/ElegantPaneli/17.jpg").default,
    require("./Img/Paneli/ElegantPaneli/18.jpg").default,
    require("./Img/Paneli/ElegantPaneli/4.jpg").default,
    require("./Img/Paneli/ElegantPaneli/6.jpg").default,
  ],
};

export default PANELI;
